// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.36;

import {ServiceRewardsActor, Share} from "../../src/ServiceRewardsActor.sol";

/// @dev Differential test harness: inherits ServiceRewardsActor, exposing the internal
///      _computeShares (largest-remainder share allocation) via a public wrapper for the
///      differential tests to call the on-chain implementation directly.
///      Difference from test/halmos/ComputeSharesHarness.sol: this harness uses a public wrapper
///      (normal EVM calls, not halmos symbolic execution); the owner is generated by SRATestBase's
///      Safe helpers, so it deploys normally under forge test.
contract DifferentialSharesHarness is ServiceRewardsActor {
    constructor(
        address o1,
        address o2,
        uint64 epochsPerQuarter,
        uint64 postPeriod,
        uint64 verificationWindow,
        uint64 cancelHold,
        uint64 activationEpoch,
        uint256 minLot,
        uint256 priceBand,
        uint256 maxPricePeriods
    )
        ServiceRewardsActor(
            o1,
            o2,
            epochsPerQuarter,
            postPeriod,
            verificationWindow,
            cancelHold,
            activationEpoch,
            minLot,
            priceBand,
            maxPricePeriods
        )
    {}

    function computeShares(address[] memory wallets, uint256[] memory usds, uint256 count, uint256 total)
        public
        pure
        returns (Share[] memory)
    {
        return _computeShares(wallets, usds, count, total);
    }
}
