// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.36;

// ============================================================================
// SRA differential tests — independent reference model cross-validation (breaking same-source bias)
//
// Background: the current test mock and the SRA implementation share the same FVMRewards encoding
// library; if the encoding library/understanding is wrong, both fail together (same-source bias,
// proven real by the A2 defect). This file uses a **fully independent Python reference model**
// (.ghost/references/014-differential/model.py, derived independently from FIP-0118's mathematical
// semantics, not reading the Solidity implementation) to cross-validate the three computation cores:
//   1. _computeShares largest-remainder share allocation (SplitRule, spec §3.2 step 4)
//   2. aggregatedFPV aggregation (sum of usdValue after finalize, spec §3.2 step 3 + §3.3)
//   3. postVolume's PRICE_BAND validation (spec §3.3 thin auction guardrail)
//
// Cases are generated by Python (seed=42 reproducible); expected values are entirely computed by the
// reference model; see test/differential/DifferentialCases.sol (AUTO-GENERATED, do not hand-edit).
// ============================================================================

import {ServiceRewardsActor, Share} from "../../src/ServiceRewardsActor.sol";
import {PricePeriod} from "../../src/lib/SraTypes.sol";
import {SRATestBase} from "../SRATestBase.sol";
import {DifferentialCases} from "./DifferentialCases.sol";
import {DifferentialSharesHarness} from "./DifferentialSharesHarness.sol";

contract DifferentialSharesTest is SRATestBase {
    DifferentialSharesHarness internal harness;

    function setUp() public override {
        super.setUp();
        harness = new DifferentialSharesHarness(
            owner1,
            owner2,
            EPOCHS_PER_QUARTER,
            POST_PERIOD,
            VERIFICATION_WINDOW,
            SRA_CANCEL_HOLD,
            ACTIVATION_EPOCH,
            MIN_LOT,
            PRICE_BAND,
            MAX_PRICE_PERIODS
        );
    }

    // ------------------------------------------------------------------------
    // 1. Largest-remainder share allocation: on-chain _computeShares output == Python reference model expectation
    // ------------------------------------------------------------------------

    function test_Diff_Share_MaxRemainder_AllCases() public view {
        DifferentialCases.ShareCase[] memory cases = DifferentialCases.shareCases();
        for (uint256 i = 0; i < cases.length; i++) {
            uint256[] memory usds = cases[i].usds;
            uint256 total;
            for (uint256 j = 0; j < usds.length; j++) {
                total += usds[j];
            }
            address[] memory wallets = _wallets(usds.length);
            Share[] memory shares = harness.computeShares(wallets, usds, usds.length, total);

            assertEq(shares.length, cases[i].expected.length, _msg("share", i, "length"));
            for (uint256 j = 0; j < shares.length; j++) {
                assertEq(shares[j].share, cases[i].expected[j], _msg("share", i, "value"));
            }
        }
    }

    // ------------------------------------------------------------------------
    // 2. FPV aggregation: post-finalize aggregatedFPV == Python reference model expectation
    //    each case deploys a fresh SRA, admits 1-4 orchestrators, postVolume (prints within a case
    //    share a uniform rate -> band always passes, focusing on the aggregation formula), then reads
    //    the aggregate after finalize.
    // ------------------------------------------------------------------------

    function test_Diff_Aggregate_Fpv_AllCases() public {
        DifferentialCases.AggCase[] memory cases = DifferentialCases.aggCases();
        for (uint256 i = 0; i < cases.length; i++) {
            ServiceRewardsActor s = _newSra(PRICE_BAND);
            DifferentialCases.Orch[] memory orchs = cases[i].orchs;

            for (uint256 k = 0; k < orchs.length; k++) {
                address orch = makeAddr(string.concat("agg-", vm.toString(i), "-", vm.toString(k)));
                _admitOn(s, orch);
                vm.roll(_qEnd(0) + 1); // within the posting window
                PricePeriod[] memory periods = new PricePeriod[](orchs[k].periods.length);
                for (uint256 m = 0; m < periods.length; m++) {
                    periods[m] =
                        _period(5000, orchs[k].periods[m].lot, orchs[k].periods[m].claim, orchs[k].periods[m].atto);
                }
                vm.prank(orch);
                s.postVolume(0, _fpvWithPeriods(orchs[k].stable, periods));
            }

            _rollTo(_qVerifyEnd(0) + 1); // post-binding
            s.finalizeConversion(0);
            assertEq(s.aggregatedFPV(0), cases[i].expected, _msg("agg", i, "aggregated"));
        }
    }

    // ------------------------------------------------------------------------
    // 3. PRICE_BAND validation: postVolume accept/revert matches the Python reference model determination
    //    each case deploys a fresh SRA (band parameterized); cross-quarter print sequence (print1 cold-start
    //    accepted -> finalize makes it the anchor -> print2 judged against the anchor -> optional print3 still
    //    judged against the anchor). Anchor semantics: the reference = the qualifying print of the previous
    //    quarter's binding final state, fixed within the quarter (prevents single-batch chained-step drift).
    // ------------------------------------------------------------------------

    function test_Diff_Band_AllCases() public {
        DifferentialCases.BandCase[] memory cases = DifferentialCases.bandCases();
        for (uint256 i = 0; i < cases.length; i++) {
            DifferentialCases.BandCase memory c = cases[i];
            ServiceRewardsActor s = _newSra(c.bandBp);

            // Quarter 0: orchestrator A posts print1 (cold-start accepted); finalize at quarter end makes it the anchor
            address a = makeAddr(string.concat("band-", vm.toString(i), "-a"));
            _admitOn(s, a);
            vm.roll(_qEnd(0) + 1);
            PricePeriod[] memory p1 = new PricePeriod[](1);
            p1[0] = _period(5000, c.lot1, c.claim1, 1e18);
            vm.prank(a);
            s.postVolume(0, _fpvWithPeriods(100e18, p1));
            assertEq(s.fpvOf(0, a).filPeriods.length, 1, _msg("band", i, "print1 cold-start accepted"));
            _rollTo(_qVerifyEnd(0) + 1);
            s.finalizeConversion(0); // anchor = print1 (qualifying print of the previous quarter's binding final state)

            // Quarter 1: orchestrator B posts print2 (judged against the anchor print1)
            address b = makeAddr(string.concat("band-", vm.toString(i), "-b"));
            _admitOn(s, b);
            vm.roll(_qEnd(1) + 1);
            PricePeriod[] memory p2 = new PricePeriod[](1);
            p2[0] = _period(6000, c.lot2, c.claim2, 1e18);
            if (c.accept2) {
                vm.prank(b);
                s.postVolume(1, _fpvWithPeriods(100e18, p2));
                assertEq(s.fpvOf(1, b).filPeriods.length, 1, _msg("band", i, "print2 within band accepted"));
            } else {
                vm.prank(b);
                vm.expectRevert();
                s.postVolume(1, _fpvWithPeriods(100e18, p2));
            }

            // Quarter 2 (optional): print3 still judged against the anchor print1 (anchor fixed within the quarter, not a reference chain)
            if (c.has3) {
                address cc = makeAddr(string.concat("band-", vm.toString(i), "-c"));
                _admitOn(s, cc);
                vm.roll(_qEnd(2) + 1);
                PricePeriod[] memory p3 = new PricePeriod[](1);
                p3[0] = _period(7000, c.lot3, c.claim3, 1e18);
                if (c.accept3) {
                    vm.prank(cc);
                    s.postVolume(2, _fpvWithPeriods(100e18, p3));
                    assertEq(s.fpvOf(2, cc).filPeriods.length, 1, _msg("band", i, "print3 within band accepted"));
                } else {
                    vm.prank(cc);
                    vm.expectRevert();
                    s.postVolume(2, _fpvWithPeriods(100e18, p3));
                }
            }
        }
    }

    // ------------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------------

    function _wallets(uint256 n) internal pure returns (address[] memory w) {
        w = new address[](n);
        for (uint256 i = 0; i < n; i++) {
            w[i] = address(uint160(i + 1)); // non-zero addresses; share assertions only inspect values
        }
    }

    function _newSra(uint256 band) internal returns (ServiceRewardsActor s) {
        s = new ServiceRewardsActor(
            owner1,
            owner2,
            EPOCHS_PER_QUARTER,
            POST_PERIOD,
            VERIFICATION_WINDOW,
            SRA_CANCEL_HOLD,
            ACTIVATION_EPOCH,
            MIN_LOT,
            band,
            MAX_PRICE_PERIODS
        );
    }

    /// @dev Runs the governance three-phase admit on the given SRA instance (the base _admit always operates on the sra instance).
    function _admitOn(ServiceRewardsActor s, address orch) internal {
        vm.prank(owner1);
        s.admit(orch);
        vm.prank(owner2);
        s.admit(orch);
        vm.roll(block.number + SRA_CANCEL_HOLD);
        s.admit(orch); // third call (permissionless) completes execution
    }

    function _msg(string memory kind, uint256 i, string memory what) internal pure returns (string memory) {
        return string.concat("differential ", kind, " case ", vm.toString(i), ": ", what);
    }
}
